app/routes.php
<?php

Route::group(
    [ 'before' => 'user' ],
    function () {

        Route::get( '/', [ 'as' => 'home', 'uses' => 'HomeController@showWelcome' ] );
        Route::get( '/help', [ 'as' => 'help', 'uses' => 'HomeController@help' ] );
        Route::get( '/work', [ 'as' => 'work', 'uses' => 'HomeController@work' ] );
        Route::get( '/moder', [ 'as' => 'moder', 'uses' => 'HomeController@moder' ] );


        Route::resource( 'pictures', 'PicturesController' );
        Route::get(
            'pictures/category/{category?}',
            [ 'as' => 'pictures.category', 'uses' => 'PicturesController@index' ]
        );

    }
);

Route::group(
    [ 'before' => 'guest', 'prefix' => 'api/v1', 'namespace' => 'Api\v1' ],
    function () {
        Route::get( 'pictures/{pictureId}/like', [ 'as' => 'pictures.like', 'uses' => 'PicturesController@like' ] );
        Route::post(
            'pictures/{pictureId}/accept',
            [ 'as' => 'pictures.accept', 'uses' => 'PicturesController@accept' ]
        );
        Route::resource( 'pictures', 'PicturesController', [ 'only' => [ 'show', 'destroy' ] ] );
        Route::resource( 'users', 'UsersController', [ 'only' => [ 'update' ] ] );
    }
);

app/controllers/HomeController.php
<?php

class HomeController extends BaseController
{

    /*
    |--------------------------------------------------------------------------
    | Default Home Controller
    |--------------------------------------------------------------------------
    |
    | You may wish to use controllers instead of, or in addition to, Closure
    | based routes. That's great! Here is an example controller method to
    | get you started. To route to this controller, just add the route:
    |
    |	Route::get('/', 'HomeController@showWelcome');
    |
    */

    public function showWelcome()
    {
        return View::make( 'home.index' );
    }

    public function help()
    {
        return View::make( 'home.help' );
    }

    public function work()
    {
        return View::make( 'home.work' );
    }

    public function moder()
    {
        $pictures = Picture::where( 'accepted', '=', false )->paginate(12);

        return View::make( 'home.moder', compact( 'pictures' ) );
    }

}

app/views/home/help.blade.php
@extends('layouts.main')

@section('title'){{ 'Помощь' }}@stop

@section('keywords'){{ 'Помощь' }}@stop

@section('description'){{ 'Помощь' }}@stop

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="page-header">
            <h2>Помощь</h2>
        </div>

        <div>
        <h3>Какие изображения лучше всего подходят для больших открыток?</h3>
        <p>
            Изображения с пропорцией 2:3 (2 к 3). 400x600 800x1200 и так далее
        </p>
        <br>

        <h3>Какие правила пользования?</h3>
        <p>
            <a target="_blank" href="http://vk.com/terms">Правила использования </a><br>
            Администрация приложения не несет ответственности за размещение контента, все вопросы связанные с этим
            направляються пользователю разместившему контент. <strong>Используя приложение вы соглашаетесь с этим</strong>.<br>
            Естественно администрация приложения по мере своих сил удаляет контент, связанный с нарушением <a target="_blank" href="http://vk.com/terms">правил использовани</a>.
        </p>
        <br>


        <h3>Почему у некоторых пользователей не запускается приложение?</h3>
        <p>
            Причина: На данном этапе мы ждем пока дедьки бюрократы изготовят нам <a target="_blank" href="https://ssl.ru/">SSL сертификат</a>
        </p>
        <p>
            То есть наше приложение не может работать по протоколу <a target="_blank" href="https://ru.wikipedia.org/wiki/HTTPS">https</a>
        </p>
        <p>
            Некоторые пользователи используют ссылку https://vk.com, заметьте есть добавочная буква s
        </p>
        <p>
            Чтобы приложение заработало
            <ul>
                <li>
                    Войдите в "Мои настройки" и отключите галочку<br>
                    <img src="{{asset('/assets/help.jpg')}}" />
                </li>
                <li>
                    Выйдите из "Вконтакте"
                </li>
                <li>
                    Перейдите на <a href="http://vk.com">http://vk.com</a> заметьте нет буквы s
                </li>
                <li>
                    Войдите в "Вконтакте" и запустите приложение
                </li>
                <li>
                    Вот и все! Желаем удачного использования
                </li>
            </ul>
        </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
@stop

app/views/home/index.blade.php
@extends('layouts.main')

@section('title'){{ 'Исполнение желаний' }}@stop

@section('keywords'){{ 'Исполнение желаний' }}@stop

@section('description'){{ 'Исполнение желаний' }}@stop

@section('content')

<div id="large-header" class="large-header">
    <canvas id="demo-canvas"></canvas>
    <h1 class="main-title">
        <span id="sectionCheck1" class="sectionCheck"></span>
        <span id="sectionCheck2" class="sectionCheck"></span>
        <span id="sectionCheck3" class="sectionCheck"></span>
        <br>
        <span id="skazka">Загадай желание</span>
        <br>
        <br>
        <button id="check" class="btn btn-info">Показать вероятность исполнения</button>
        <br>
        <br>
        <span class="thin">Совпадения: 2 - 50%, 3 - 100%</span>
    </h1>
</div>
<script src="/assets/header/TweenLite.min.js"></script>
<script src="/assets/header/EasePack.min.js"></script>
<script src="/assets/header/rAF.js"></script>
<script src="/assets/header/demo-1.js"></script>
@stop



@section('scripts')
<script>
    $().ready(function(){
        $('#sectionCheck1').hide();
        $('#sectionCheck2').hide();
        $('#sectionCheck3').hide();

        $('#check').click(function(e){
           e.preventDefault();
           $('#check').hide();
           $('#skazka').hide();

           $('#sectionCheck1').show();
           $('#sectionCheck2').show();
           $('#sectionCheck3').show();


            var min=0;
            var max = 9;

            var timer = 0;
            var checkTimer = 20;

            var result = setInterval(function(){
                if(timer>checkTimer){
                    clearInterval(result);
                    $('#check').show();
                    $('#skazka').show().html('Загадать еще одно');
                    timer=0;
                }

                $('#sectionCheck1').html(Math.floor(Math.random() * (max - min + 1)) + min);
                $('#sectionCheck2').html(Math.floor(Math.random() * (max - min + 1)) + min);
                $('#sectionCheck3').html(Math.floor(Math.random() * (max - min + 1)) + min);
                if($('#sectionCheck1').html()==$('#sectionCheck2').html() || $('#sectionCheck2').html()==$('#sectionCheck3' ).html() || $('#sectionCheck1').html()==$('#sectionCheck2').html()){
                    var bingo = Math.floor(Math.random() * (max - min + 1)) + min;
                    $('#sectionCheck1').html(bingo);
                    $('#sectionCheck2').html(bingo);
                    $('#sectionCheck3').html(bingo);
                }
                timer++;
            }, 80);

        });
    });
</script>
@stop

app/views/home/moder.blade.php
@extends('layouts.main')

@section('title'){{ 'Работа в России' }}@stop

@section('keywords'){{ 'Работа в России' }}@stop

@section('description'){{ 'Работа в России' }}@stop

@section('content')
<div class="row" ng-controller="ModerController">
    <div class="col-xs-12">
        <div class="page-header">
            <h2>Изображения для проверки</h2>
        </div>

        @if($pictures->count())
            <div>
                <div class="row">
                            <div class="col-xs-12">
                                {{ $pictures->links() }}
                            </div>
                        </div>

                <div class="row">
                @foreach ($pictures as $picture)
                    <div class="col-xs-4" style="min-height: 400px;" id="picture{{$picture->id}}">
                        <div>
                            <a href="{{route('pictures.show', [$picture->id])}}">
                                <img class="img-responsive" src="{{'/'.$picture->path}}">
                            </a>
                        </div>
                        <div>
                            Разместил: <a target="_blank" href="http://vk.com/id{{$picture->user->vk->id}}">{{$picture->user->vk->first_name}} {{$picture->user->vk->last_name}}</a>
                        </div>
                        <div>
                            Категория: {{$picture->category->title}}
                        </div>
                        <div>
                            <button ng-click="acceptPicture({{$picture->id}})" class="btn btn-success">Принять</button>
                            <button ng-click="deletePicture({{$picture->id}})" class="btn btn-danger">Удалить</button>
                        </div>
                        <hr>
                    </div>
                @endforeach
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        {{ $pictures->links() }}
                    </div>
                </div>

            </div>
        @else
            Ничего нет
        @endif

    </div>
</div>
<br>
<br>
<br>
@stop

app/views/home/work.blade.php
@extends('layouts.main')

@section('title'){{ 'Работа в России' }}@stop

@section('keywords'){{ 'Работа в России' }}@stop

@section('description'){{ 'Работа в России' }}@stop

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="page-header">
            <h2>Работа в России</h2>
        </div>

        <div>
            <h3>В поиске работы или сотрудников?</h3>
            <p>
                У нас есть еще одно замечательное приложение <a target="_blank" href="http://vk.com/app4557309">Работа в России</a><br>
            </p>

        </div>
    </div>
</div>
<br>
<br>
<br>
@stop